pipeline {
    agent {
       // restircting the job to run certain agents which matches the label
       // label 'agent1' 
       docker {
           image 'maven:3.3.3'
           args '-v /root/.m2:/root/.m2'
       }
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('test') {
            steps {
                sh 'mvn test'
            }
            post {
              always {
                  junit 'target/surefire-reports/*.xml'   
              }
            }
        }
        stage('deploy') {
            steps {
                sh 'chmod +x ./deliver.sh && ./deliver.sh'
            }
        }
    }
}
